---
- name: reset cluster
  hosts: k8s-dev
  gather_facts: no

  tasks:
  - name: reset kube
    command: timeout -k 400s 400s kubeadm reset -f

  - name: kubelet deinstall
    ansible.builtin.dpkg_selections:
      name: kubelet
      selection: deinstall

  - name: kubeadm deinstall
    ansible.builtin.dpkg_selections:
      name: kubeadm
      selection: deinstall

  - name: kubectl deinstall
    ansible.builtin.dpkg_selections:
      name: kubectl
      selection: deinstall

  - name: Delete packages
    ansible.builtin.apt:
      name: "{{ packages }}"
      state: absent
      update_cache: yes
    vars:
      packages:
      - kubelet  
      - kubeadm
      - kubectl
      - containerd

  - name: Delete containerd module
    ansible.builtin.file:
      name: /etc/modules-load.d/containerd.conf
      state: absent

  - name: Delete kubernetes-cri module
    ansible.builtin.file:
      name: /etc/modules-load.d/99-kubernetes-cri.conf
      state: absent

  - name: Sysctl apply
    shell: sysctl --system

  - name: Delete gpg
    ansible.builtin.apt_key:
      url: https://packages.cloud.google.com/apt/doc//apt-key.gpg.asc
      state: absent

  - name: Delete kubernetes repo
    ansible.builtin.apt_repository:
      repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
      state: absent

  - name: rm files
    file:
      dest: "{{item}}"
      state: absent
    with_items:
      - "/var/lib/kubelet"
      - "/etc/kubernetes"
      - "$HOME/.kube"
      - "/etc/containerd"

  - reboot:
      reboot_timeout: 1800