---
- name: K8s Defaults
  hosts: 
    - k8s-dev
  roles:
    - kubernetes-defaults

- name: K8s master init
  hosts:
    - k8s-master
  roles:
    - kubernetes-masters

- name: K8s node join
  hosts:
    - k8s-worker
  roles:
    - kubernetes-workers