---
- name: Copy kubeadm init config
  ansible.builtin.template:
    src: kubeadm-config.j2
    dest: /root/kubeadm-config.yaml
    mode: 0755

- name: Initialize the Kubernetes cluster using kubeadm
  ansible.builtin.command: kubeadm init --config /root/kubeadm-config.yaml
  changed_when: false

- name: Setup admin conf
  ansible.builtin.shell: "{{ item }}"
  with_items:
    - mkdir -p $HOME/.kube
    - cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    - sudo chown $(id -u):$(id -g) $HOME/.kube/config

- name: Copy Flannel deployment
  ansible.builtin.template:
    src: kube-flannel_v0.19.0.j2
    dest: /root/flannel.yaml
    mode: 0755

- name: Flannel deploy
  ansible.builtin.command: kubectl apply -f /root/flannel.yaml
  changed_when: false

- name: Generate join command
  ansible.builtin.command: kubeadm token create --print-join-command
  register: join_command
  changed_when: false

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }} --cri-socket=/run/containerd/containerd.sock" dest="./join-command"
